services:

  example:
    # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
    image: webdevops/php-nginx-dev:8.1
    container_name: example
    volumes:
      - .:/rootapp
      - ./.docker/nginx/docker-nginx.conf:/opt/docker/etc/nginx/vhost.conf
    working_dir: /rootapp
    env_file:
      - ./.env
    environment:
      # PHP config
      # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: "on"
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 86400
      PHP_REQUEST_TERMINATE_TIMEOUT: 86400
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      php.xdebug.var_display_max_depth: 10
      php.xdebug.var_display_max_data: 2048
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=Host(`example.localhost`)|| HostRegexp(`media[1-3]\.example\.localhost`)
      - traefik.http.routers.example.entrypoints=http
      - traefik.http.routers.example-secure.rule=Host(`example.localhost`) || HostRegexp(`media[1-3]\.example\.localhost`)
      - traefik.http.routers.example-secure.tls=true
      - traefik.http.routers.example-secure.entrypoints=https
    networks:
      - docker-traefik-local-main_reverse_proxy

networks:
  docker-traefik-local-main_reverse_proxy:
    external: true
