[global]
    sendAnonymousUsage = false

[log]
    level = "DEBUG"
    format = "common"

[api]
    dashboard = true
    insecure = true

[providers]
    [providers.file]
        filename = "/etc/traefik/template-rules.toml"
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
        network = "traefik"
        exposedByDefault = true

[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.https]
        address = ":443"